#
###################################
# Site wide configuration
####################################
#
title:       "Liuqinh2s' Homepage"
description: "Interested in Virtual Reality & Augment Reality & Artificial Intelligence"
baseurl:
url:         # the base hostname & protocol for your site
img_url: /imgs

#
###################################
# Jekyll configuration
####################################
#
# timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       pygments
excerpt_separator: <!--more-->
permalink:         /:year/:month/:title/
timezone:          Asia/Shanghai

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Liuqinh2s
  avatar: avatar.jpg
  # job: "小溪之歌"
  bio: "Interested in Virtual Reality & Augment Reality & Artificial Intelligence"

  github: liuqinh2s #username
  weibo: liuqinh2s #username
  zhihu: liuqinh2s
  # facebook: liuqinh2s
  email: liuqinh2s@gmail.com
  duoshuo: liuqinh2s #多说域名

  google:
    plus: #username
    analytics: UA-62251910-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  disqus-shortname: #username
  twitter:  #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  flickr: #username
  codepen: #username
