#
###################################
# Site wide configuration
####################################
#
title:       "Liuqinh2s' Homepage"
description: 现代魔法\探险者的人生手册\未来学家
baseurl:
url: "https://liuqinh2s.github.io"         # the base hostname & protocol for your site
img_url: /imgs

#
###################################
# Jekyll configuration
####################################
#
# timezone:          Asia/Shanghai
markdown:          kramdown
excerpt_separator: <!--more-->
permalink:         /:year/:month/:title/
timezone:          Asia/Shanghai

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Liuqinh2s
  avatar: Avatar.jpg
  # job: "小溪之歌"
  bio: 现代魔法/探险者的人生手册/未来学家

  github: liuqinh2s #username
  weibo: liuqinh2s #username
  zhihu: liuqinh2s
  # facebook: liuqinh2s
  email: liuqinh2s@gmail.com
  duoshuo: liuqinh2s #多说域名

# 网站统计
analytics:
    baidu:
        siteid: 653ac617693f8e980ba23a59d898f2ba        # 百度统计 js 代码后的字符串

  google:
    plus: #username
    analytics: UA-62251910-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  disqus-shortname: liuqinh2s
  twitter:  #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  flickr: #username
  codepen: #username
